//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurfUsMatchPuller.Classes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChampionHistory
    {
        public int Id { get; set; }
        public int VersionId { get; set; }
        public int ChampionId { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Blurb { get; set; }
        public string ImageName { get; set; }
        public int Attack { get; set; }
        public int Defense { get; set; }
        public int Difficulty { get; set; }
        public int Magic { get; set; }
        public string Lore { get; set; }
        public string Partype { get; set; }
        public string Key { get; set; }
        public decimal Armor { get; set; }
        public decimal ArmorPerLevel { get; set; }
        public decimal AttackDamage { get; set; }
        public decimal AttackDamagePerLevel { get; set; }
        public decimal AttackRange { get; set; }
        public decimal AttackSpeedOffset { get; set; }
        public decimal AttackSpeedPerLevel { get; set; }
        public decimal Crit { get; set; }
        public decimal CritPerLevel { get; set; }
        public decimal Hp { get; set; }
        public decimal HpPerLevel { get; set; }
        public decimal HpRegen { get; set; }
        public decimal HpRegenPerLevel { get; set; }
        public decimal MoveSpeed { get; set; }
        public decimal Mp { get; set; }
        public decimal MpPerLevel { get; set; }
        public decimal MpRegen { get; set; }
        public decimal MpRegenPerLevel { get; set; }
        public decimal SpellBlock { get; set; }
        public decimal SpellBlockPerLevel { get; set; }
        public System.DateTime LastUpdated { get; set; }
    }
}
