//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurfUsMatchPuller.Classes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChampionSpell
    {
        public int SpellId { get; set; }
        public int ChampionId { get; set; }
        public string Key { get; set; }
        public string Name { get; set; }
        public string CooldownBurn { get; set; }
        public string CostBurn { get; set; }
        public string CostType { get; set; }
        public string Description { get; set; }
        public byte MaxRank { get; set; }
        public string RangeBurn { get; set; }
        public string Resource { get; set; }
        public string SanitizedDescription { get; set; }
        public string SanitizedToolTip { get; set; }
        public string ToolTip { get; set; }
        public byte SpellSlot { get; set; }
        public string ImageName { get; set; }
    }
}
