//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurfUsMatchPuller.Classes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChampionSkin
    {
        public int SkinId { get; set; }
        public int ChampionId { get; set; }
        public byte Num { get; set; }
        public string Name { get; set; }
    }
}
