//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurfUsMatchPuller.Classes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameParticipant
    {
        public long Id { get; set; }
        public long GameId { get; set; }
        public int SummonerId { get; set; }
        public int ParticipantId { get; set; }
        public byte TeamId { get; set; }
        public int ChampionId { get; set; }
        public byte Spell1Id { get; set; }
        public byte Spell2Id { get; set; }
    }
}
