//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurfUsMatchPuller.Classes.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NurfUsEntities : DbContext
    {
        public NurfUsEntities()
            : base("name=NurfUsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APIRespons> APIResponses { get; set; }
        public virtual DbSet<ChampionExtraInfo> ChampionExtraInfoes { get; set; }
        public virtual DbSet<ChampionHistory> ChampionHistories { get; set; }
        public virtual DbSet<Champion> Champions { get; set; }
        public virtual DbSet<ChampionSkinHistory> ChampionSkinHistories { get; set; }
        public virtual DbSet<ChampionSkin> ChampionSkins { get; set; }
        public virtual DbSet<ChampionSpellHistory> ChampionSpellHistories { get; set; }
        public virtual DbSet<ChampionSpell> ChampionSpells { get; set; }
        public virtual DbSet<GameParticipant> GameParticipants { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Summoner> Summoners { get; set; }
        public virtual DbSet<SummonerSearch> SummonerSearches { get; set; }
        public virtual DbSet<Version> Versions { get; set; }
    }
}
