//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurfUsMatchPuller.Classes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Summoner
    {
        public int Id { get; set; }
        public int SummonerId { get; set; }
        public string Name { get; set; }
        public Nullable<byte> Level { get; set; }
        public Nullable<System.DateTime> RevisionDate { get; set; }
        public Nullable<int> SearchId { get; set; }
        public string Rank { get; set; }
        public Nullable<int> ProfileIconId { get; set; }
        public string Region { get; set; }
    }
}
