//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NurfUsMatchPuller.Classes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Version
    {
        public int Id { get; set; }
        public string Version1 { get; set; }
        public System.DateTime DateStamp { get; set; }
    }
}
